# Generated by Django 4.1.2 on 2022-12-04 00:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="Nome"
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=16
                    ),
                ),
                (
                    "partial_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=16
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="category.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ("name",),
            },
        ),
    ]
