# Generated by Django 4.1.2 on 2022-11-23 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_listitem"),
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=64, verbose_name="Nome"),
                ),
                (
                    "description",
                    models.CharField(max_length=256, verbose_name="Desrição"),
                ),
                ("slug", models.SlugField(max_length=64)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.image",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="category.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ("name",),
            },
        ),
    ]
