# Generated by Django 4.1.2 on 2022-10-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        editable=False, verbose_name="Última atualização em"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Nome")),
                ("path", models.CharField(max_length=256, verbose_name="Caminho")),
            ],
            options={
                "verbose_name": "Imagem",
                "verbose_name_plural": "Imagens",
                "ordering": ("name",),
            },
        ),
    ]
