# Generated by Django 4.1.2 on 2022-10-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Nome")),
                ("path", models.CharField(max_length=256, verbose_name="Caminho")),
            ],
            options={
                "verbose_name": "Imagem",
                "verbose_name_plural": "Imagens",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Warframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Posição"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Nome")),
                (
                    "warframe_type",
                    models.CharField(
                        choices=[("common", "Comum"), ("prime", "Prime")],
                        default="common",
                        max_length=8,
                        verbose_name="Tipo de Warframe",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Warframe",
                "verbose_name_plural": "Warframes",
                "ordering": ("position",),
            },
        ),
    ]
