# Generated by Django 4.1.2 on 2022-10-27 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Posição"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Nome")),
                (
                    "css_class",
                    models.CharField(max_length=64, verbose_name="Classe do CSS"),
                ),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Posição"),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Título")),
                (
                    "published_in",
                    models.CharField(max_length=64, verbose_name="Publicação"),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                ("badges", models.ManyToManyField(to="core.badge")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias",
                "ordering": ("position",),
            },
        ),
    ]
