# Generated by Django 4.1.2 on 2022-10-28 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_badge_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Posição"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "published_in",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Publicação"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("hg", "Home Item"),
                            ("hi", "Home Imagem"),
                            ("hsi", "Home Sub-Imagem"),
                            ("ai", "About Item"),
                            ("di", "Download Item"),
                        ],
                        default="hg",
                        max_length=8,
                        verbose_name="Tipo de Item",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ("position",),
            },
        ),
    ]
